packages:
  - apps/*
  - packages/*

engineStrict: true
managePackageManagerVersions: false
nodeVersion: 24.16.0
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
packageManagerStrictVersion: true
savePrefix: ''
strictPeerDependencies: true
