packages:
  - apps/*
  - packages/*

engineStrict: true
managePackageManagerVersions: false
nodeVersion: 24.16.0
onlyBuiltDependencies:
  - '@nestjs/core'
packageManagerStrictVersion: true
savePrefix: ''
strictPeerDependencies: true
