export const AUDIT_ACTIONS = [
  'identity.user_registered',
  'identity.user_logged_in',
  'identity.session_refreshed',
  'identity.session_logged_out',
  'workspace.updated',
  'access.api_key_created',
  'access.api_key_revoked',
  'workflow.created',
  'workflow.updated',
  'workflow.published',
  'workflow.test_contract.created',
  'workflow.secret_upserted',
  'workflow.secret_deleted',
  'connector.credential_upserted',
  'connector.credential_deleted',
  'ingestion.webhook_received',
  'automation.bridge_request_received',
  'execution.created',
  'execution.enqueued',
  'execution.started',
  'execution.retrying',
  'execution.dead_lettered',
  'execution.manual_retry_requested',
  'execution.succeeded',
  'execution.failed',
  'billing.webhook_received',
  'billing.event_processed',
] as const;

export const AUDIT_ENTITY_TYPES = [
  'user',
  'session',
  'workspace',
  'api_key',
  'workflow',
  'workflow_secret',
  'connector_credential',
  'webhook_request',
  'execution',
  'billing_event',
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[number];
